### PR TITLE
Realtime CPU load and Sound  level monitors

### PR DESCRIPTION
**Pull request by dcerisano**
Just submitting examples of realtime msi-rgb:
- RGB-CPU meter (blowtorch effect)
- RGB-VuMeter (white effect)

These are bash scripts that can easily be used as a template for any other realtime effects.
Instructions are given to set these scripts as autostart system services.

As services these do have some CPU overhead at their current sample rates of 100ms.

On a single Ryzen core, the RGB-CPU load meter is around 2% and the RGB-VuMeter is around 5% (which can be reduced at the cost of sensitivity). 

They can also also be run at the same time, although these particular effects do not really "go together". 

Switching the RGB-VuMeter to the ALSA mixer's microphone input is a particularly strange experience.

### CODE REVIEW

**Comment by dcerisano** [comment]
Note that only the script (msi-rgb-cpu-blowtorch.sh) should be pulled. 
The changes to main.rs are specifically for my B350M Mortar,

**Comment by nagisa** [comment]
Okay, so I don’t think that this repository is a good location for scripts like these. Ideally you would put this script up on its own repository somewhere and I would gladly link to it prominently from README. How’s that sound?

**Comment by nagisa** [comment]
That being said, I’m certainly interested in your Mortar changes. I will test them with my arctic whenever I get around to opening my case and plugging the RGB header back in.

**Comment by dcerisano** [comment]
Ok, but so I don't hog all the RGB glory I shall also link to your repo.
I want to do an OpenGL GUI and also cross compile a  Windows RGB service as well, which Rust seems to be capable of ..

**Comment by nagisa** [comment]
Windows support is fairly involving and is being tracked at https://github.com/nagisa/msi-rgb/issues/3.

**Pull request closed without merging**
